version: '3'
services:
  mysqlcontainer:
    image: vishwatejach/mydiningdatabase:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydining
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - networkmysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  frontend:
    image: vishwatejach/mydiningfrontend:latest
    ports:
      - '3001:3000'
    # environment:
    #   - REACT_APP_BACKEND_URL=http://localhost:8080
    networks:
      - networkmysql
  backend:
    image: vishwatejach/mydiningbackend1:latest
    ports:
      - '8080:8080'
    environment:
      - MYSQL_HOST=mysqlcontainer
      - MYSQL_PORT=3306
      - MYSQL_DB_NAME=mydining
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - networkmysql
    depends_on:
      - mysqlcontainer
    volumes:
    - ./spebackend/images:/images
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  networkmysql:
volumes:
  mysql_data:
