---
- name: Build Docker Images
  hosts: localhost
  tasks:
    - name: Build Backend Image
      community.docker.docker_image_build:
        path: ../spebackend
        name: vishwatejach/mydiningbackend1
        tag: latest

    - name: Build Frontend Image
      community.docker.docker_image_build:
        path: ../spefrontend
        name: vishwatejach/mydiningfrontend
        tag: latest

    - name: Build Database Image
      community.docker.docker_image_build:
        path: ../spedatabase
        name: vishwatejach/mydiningdatabase
        tag: latest
