---
- name: Build and Push Docker Images
  hosts: all
  vars:
    docker_images:
      - name: vishwatejach/mydiningbackend1
        build:
          path: ../spebackend
          source: build
      - name: vishwatejach/mydiningfrontend
        build:
          path: ../spefrontend
          source: build
      - name: vishwatejach/mydiningdatabase
        build:
          path: ../spedatabase
          source: build
  tasks:
    - name: Build Docker images
      community.docker.docker_image:
        path: "{{ item.build.path }}"
        name: "{{ item.name }}"
        state: present
      loop: "{{ docker_images }}"
      become: yes
