---
- name: Build and Push Docker Images
  hosts: localhost
  gather_facts: no
  vars:
    dockerhub_username: vishwatejach
    dockerhub_password: Vinnusri@0102

  tasks:
    - name: Build Docker Images
      docker_image:
        source: build
        path: ../spebackend
        name: vishwatejach/mydiningbackend1
        tag: latest
      register: backend_image

    - name: Build Docker Image for frontend
      docker_image:
        source: build
        path: ../spefrontend
        name: vishwatejach/mydiningfrontend
        tag: latest
      register: frontend_image

    - name: Build Docker Image for database
      docker_image:
        source: build
        path: ../spedatabase
        name: vishwatejach/mydiningdatabase
        tag: latest
      register: database_image

    - name: Push Docker Images to DockerHub
      shell: |
        echo "{{ dockerhub_password }}" | docker login --username "{{ dockerhub_username }}" --password-stdin

    - name: Push Backend Image
      shell: docker push vishwatejach/mydiningbackend1:latest

    - name: Push Frontend Image
      shell: docker push vishwatejach/mydiningfrontend:latest

    - name: Push Database Image
      shell: docker push vishwatejach/mydiningdatabase:latest
