---
- name: Build and Push Docker Images
  hosts: localhost
  gather_facts: no
  vars:
    dockerhub_username: vishwatejach
    dockerhub_password: Vinnusri@0102

  tasks:
    - name: Build Docker Images
      docker_image:
        path: ../spebackend
        name: vishwatejach/mydiningbackend1
        tag: latest
      register: backend_image

    - name: Build Docker Image for frontend
      docker_image:
        path: ../spefrontend
        name: vishwatejach/mydiningfrontend
        tag: latest
      register: frontend_image

    - name: Build Docker Image for database
      docker_image:
        path: ../spedatabase
        name: vishwatejach/mydiningdatabase
        tag: latest
      register: database_image

    - name: Push Docker Images to DockerHub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Push Backend Image
      docker_push:
        name: "{{ backend_image.image_name }}"
        tag: "{{ backend_image.image_tag }}"

    - name: Push Frontend Image
      docker_push:
        name: "{{ frontend_image.image_name }}"
        tag: "{{ frontend_image.image_tag }}"

    - name: Push Database Image
      docker_push:
        name: "{{ database_image.image_name }}"
        tag: "{{ database_image.image_tag }}"

