---
- name: Build and Push Docker Images
  hosts: localhost
  gather_facts: no
  vars:
    dockerhub_username: your_username
    dockerhub_password: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              36303363316462303064386131376637343766383730653833653830656538633033303662323465
              6337643661306634343661666433626334636536663165650a396136306635393563616639643566
              61393930373935666432326661613136623334313637336630353762656562323936316265323732
              6164313964346664370a306164643062653030396633633331636536316239333436346433353030
              3936

  tasks:
    - name: Build Docker Images
      docker_image:
        path: ../spebackend
        name: vishwatejach/mydiningbackend1
        tag: latest
      register: backend_image

    - name: Build Docker Image for frontend
      docker_image:
        path: ../spefrontend
        name: vishwatejach/mydiningfrontend
        tag: latest
      register: frontend_image

    - name: Build Docker Image for database
      docker_image:
        path: ../spedatabase
        name: vishwatejach/mydiningdatabase
        tag: latest
      register: database_image

    - name: Push Docker Images to DockerHub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Push Backend Image
      docker_push:
        name: "{{ backend_image.image_name }}"
        tag: "{{ backend_image.image_tag }}"

    - name: Push Frontend Image
      docker_push:
        name: "{{ frontend_image.image_name }}"
        tag: "{{ frontend_image.image_tag }}"

    - name: Push Database Image
      docker_push:
        name: "{{ database_image.image_name }}"
        tag: "{{ database_image.image_tag }}"

