---
- name: Build and Push Docker Images
  hosts: localhost
  gather_facts: no
  vars:
    dockerhub_username: vishwatejach
    dockerhub_password: Vinnusri@0102

  tasks:
    - name: Build Docker Images
      community.docker.docker_image:
        source: build
        build:
          path: ../spebackend
        name: vishwatejach/mydiningbackend1:latest
      register: backend_image

    - name: Build Docker Image for frontend
      community.docker.docker_image:
        source: build
        build:
          path: ../spefrontend
        name: vishwatejach/mydiningfrontend:latest
      register: frontend_image

    - name: Build Docker Image for database
      community.docker.docker_image:
        source: build
        build:
          path: ../spedatabase
        name: vishwatejach/mydiningdatabase:latest
      register: database_image

    - name: Push Docker Images to DockerHub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Push Backend Image
      community.docker.docker_push:
        name: "{{ backend_image.name }}"
        tag: "{{ backend_image.tag }}"

    - name: Push Frontend Image
      community.docker.docker_push:
        name: "{{ frontend_image.name }}"
        tag: "{{ frontend_image.tag }}"

    - name: Push Database Image
      community.docker.docker_push:
        name: "{{ database_image.name }}"
        tag: "{{ database_image.tag }}"
