---
- name: Build and Push Docker Images
  hosts: all
  vars:
    docker_images:
      - name: vishwatejach/mydiningbackend1
        path: ../spebackend
      - name: vishwatejach/mydiningfrontend
        path: ../spefrontend
      - name: vishwatejach/mydiningdatabase
        path: ../spedatabase
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Build Docker images
      community.docker.docker_image:
        with_items: "{{ docker_images }}"
        loop: "{{ docker_images }}"
        path: "{{ item.path }}"
        name: "{{ item.name }}"
        state: present
      become: yes
