---
- name: Push Docker Images to Docker Hub
  hosts: localhost
  vars_files:
    - vault.yaml
  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"
        
    - name: Push Images to Docker Hub
      community.docker.docker_image_push:
        name: "{{ item.name }}"
        tag: latest
      loop:
        - { name: vishwatejach/mydiningbackend1 }
        - { name: vishwatejach/mydiningfrontend }
        - { name: vishwatejach/mydiningdatabase }
